version: '3'
services:
  db:
    image: mysql
    restart: always

    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=springuser
      - MYSQL_PASSWORD=ThePassword
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 20s
      timeout: 30s
      retries: 10


  product-service:
    depends_on:
      db:
        condition: service_healthy # wait until the mysql service becomes healthy
#    image: ghcr.io/ruckel/product-service:latest   # "image" OR "build"
    build:
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"


  orders-service:
    depends_on:
      db:
        condition: service_healthy # wait until the mysql service becomes healthy
#    image: ghcr.io/ruckel/orders-service:latest   # "image" OR "build"
    build:
      context: ./orders-service
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
   
  customer-service:

    depends_on:
      db:
        condition: service_healthy # wait until the mysql service becomes healthy
#    image: ghcr.io/ruckel/customer-service:latest   # "image" OR "build"
    build:
      context: ./customer-service
      dockerfile: Dockerfile
    ports:
      - "8082:8080"